#!/usr/bin/env node

/**
 * scripts/audit_leak.js
 * 
 * One-Click Forensic Leak Audit Script
 * 
 * Analyzes a leaked audio file (WAV, MP3, AAC, M4A), extracts the embedded
 * acoustic watermark ID, and matches it against a distribution manifest
 * (recipients.json) to identify the exact recipient responsible for the leak.
 * 
 * Usage:
 *   node scripts/audit_leak.js <leaked_audio> --manifest <recipients.json>
 */

import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { execSync } from "node:child_process";
import { readWavFile } from "../src/wav.js";
import { detectWatermark } from "../src/detect.js";

function printHelp() {
  console.log(`
Aureal Watermark — Forensic Leak Audit Tool

Usage:
  node scripts/audit_leak.js <leaked_audio> --manifest <recipients.json> [options]

Options:
  --manifest <path>   Path to recipients.json generated by batch_distribute.js
  --key <str>         Watermark secret key (defaults to manifest key)
  --band <band>       Carrier band: auto, dual, high, mid (default: auto)
  --json              Output raw JSON report instead of human-readable report

Examples:
  node scripts/audit_leak.js leaked_rip.wav --manifest ./promos/recipients.json
  node scripts/audit_leak.js leaked_leak.mp3 --manifest ./promos/recipients.json
`);
}

function decodeAudioToWav(inputPath) {
  const ext = path.extname(inputPath).toLowerCase();
  if (ext === ".wav") {
    return { wavPath: inputPath, isTemp: false };
  }

  // Check ffmpeg for compressed audio (MP3, AAC, M4A, etc.)
  const tempWav = path.join(os.tmpdir(), `aureal_audit_${Date.now()}_${Math.random().toString(36).slice(2)}.wav`);
  try {
    execSync(`ffmpeg -v error -y -i "${inputPath}" -acodec pcm_s16le -ar 44100 "${tempWav}"`, { stdio: "pipe" });
    return { wavPath: tempWav, isTemp: true };
  } catch (err) {
    throw new Error(`Failed to decode non-WAV audio (${ext}). Ensure ffmpeg is installed, or convert to WAV first.`);
  }
}

async function main() {
  const args = process.argv.slice(2);
  if (args.length === 0 || args.includes("--help") || args.includes("-h")) {
    printHelp();
    process.exit(0);
  }

  const audioFile = args[0].startsWith("--") ? null : args[0];
  if (!audioFile) {
    console.error("Error: Leaked audio file required as first argument.");
    printHelp();
    process.exit(1);
  }

  const flags = {};
  for (let i = 1; i < args.length; i++) {
    if (args[i].startsWith("--")) {
      const key = args[i].slice(2);
      const next = args[i + 1];
      if (next && !next.startsWith("--")) {
        flags[key] = next;
        i++;
      } else {
        flags[key] = true;
      }
    }
  }

  if (!flags.manifest) {
    console.error("Error: --manifest <recipients.json> is required.");
    printHelp();
    process.exit(1);
  }

  if (!fs.existsSync(audioFile)) {
    console.error(`Error: Audio file not found: ${audioFile}`);
    process.exit(1);
  }

  if (!fs.existsSync(flags.manifest)) {
    console.error(`Error: Manifest file not found: ${flags.manifest}`);
    process.exit(1);
  }

  // Load manifest
  let manifest;
  try {
    manifest = JSON.parse(fs.readFileSync(flags.manifest, "utf8"));
  } catch (e) {
    console.error(`Failed to parse manifest JSON: ${e.message}`);
    process.exit(1);
  }

  const idMap = new Map();
  if (Array.isArray(manifest.recipients)) {
    for (const r of manifest.recipients) {
      idMap.set(r.id, r);
    }
  }

  const key = flags.key || manifest.key || undefined;
  const band = flags.band || manifest.band || "auto";

  // Decode audio
  const { wavPath, isTemp } = decodeAudioToWav(audioFile);
  let wav;
  try {
    wav = await readWavFile(wavPath);
  } finally {
    if (isTemp && fs.existsSync(wavPath)) {
      try { fs.unlinkSync(wavPath); } catch (_) {}
    }
  }

  // Run detection
  const format = { sampleRate: wav.sampleRate, channels: wav.channels };
  const res = detectWatermark(wav.samples, format, {
    key,
    band
  });

  const recoveredId = res.recoveredPayloadId;
  const matchedRecipient = recoveredId != null ? idMap.get(recoveredId) : null;

  if (flags.json) {
    console.log(JSON.stringify({
      auditTarget: audioFile,
      fileInfo: {
        sampleRate: wav.sampleRate,
        channels: wav.channels,
        durationSec: wav.durationSec
      },
      detection: res,
      leakMatch: matchedRecipient || null,
      verdict: matchedRecipient
        ? `Audio leaked from recipient "${matchedRecipient.name}" (ID #${matchedRecipient.id})`
        : (res.detected ? "Watermark detected but ID not found in manifest" : "No watermark detected")
    }, null, 2));
    process.exit(res.detected ? 0 : 1);
  }

  console.log(`\n======================================================`);
  console.log(`AUREAL FORENSIC AUDIT REPORT`);
  console.log(`======================================================`);
  console.log(`Target File:      ${audioFile}`);
  console.log(`Audio Format:     ${wav.sampleRate} Hz, ${wav.channels}ch, ${wav.durationSec.toFixed(1)}s`);

  if (!res.detected) {
    console.log(`Status:           NO WATERMARK DETECTED`);
    console.log(`Confidence:       ${(res.confidence * 100).toFixed(1)}%`);
    console.log(`======================================================\n`);
    process.exit(1);
  }

  const ebn0Str = res.ebN0Db != null ? `${res.ebN0Db > 0 ? "+" : ""}${res.ebN0Db} dB` : "-";
  const sqnrStr = res.sqnrDb != null ? `${res.sqnrDb > 0 ? "+" : ""}${res.sqnrDb} dB` : "-";

  console.log(`Status:           WATERMARK VERIFIED`);
  console.log(`Recovered ID:     #${recoveredId}`);
  console.log(`Confidence:       ${(res.confidence * 100).toFixed(1)}%`);
  console.log(`Signal Margin:    Eb/N0: ${ebn0Str} (SQNR: ${sqnrStr})`);
  console.log(`Bit Error Rate:   ${(res.ber * 100).toFixed(1)}% (${res.crcOk ? "CRC-16 Valid" : "CRC Error"})`);
  console.log(`Repetitions:      ${res.reps} frames integrated`);
  if (res.details && res.details.bitsCorrected) {
    console.log(`Error Correction: Repaired ${res.details.bitsCorrected.length}-bit flip at symbol(s) ${res.details.bitsCorrected.join(", ")}`);
  }

  console.log(`------------------------------------------------------`);
  if (matchedRecipient) {
    console.log(`MATCH CONFIRMED IN DISTRIBUTION MANIFEST:`);
    console.log(`  Recipient Name:   ${matchedRecipient.name}`);
    console.log(`  Assigned ID:      #${matchedRecipient.id}`);
    if (matchedRecipient.filename) {
      console.log(`  Original File:    ${matchedRecipient.filename}`);
    }
    if (matchedRecipient.sha256) {
      console.log(`  Original SHA256:  ${matchedRecipient.sha256}`);
    }
    if (manifest.generatedAt) {
      console.log(`  Distributed At:   ${manifest.generatedAt}`);
    }
    console.log(`======================================================`);
    console.log(`VERDICT: Leak traced directly to "${matchedRecipient.name}".\n`);
  } else {
    console.log(`MANIFEST LOOKUP:`);
    console.log(`  No recipient found in manifest matching ID #${recoveredId}.`);
    console.log(`======================================================\n`);
  }

  process.exit(0);
}

main().catch((err) => {
  console.error("Forensic audit error:", err);
  process.exit(1);
});
